services:
  app_proxy:
    environment:
      APP_HOST: felipe-qbittorrent_gluetun_1
      APP_PORT: 8080

  gluetun:
    image: qmcgaw/gluetun:latest
    restart: on-failure

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

    # Credenciais NordVPN ficam SOMENTE no Umbrel
    env_file:
      - ${APP_DATA_DIR}/data/gluetun/nordvpn.env

    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - TZ=Europe/Lisbon

    volumes:
      - ${APP_DATA_DIR}/data/gluetun:/gluetun

  server:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: on-failure

    # qBittorrent usa exclusivamente a rede do Gluetun
    network_mode: "service:gluetun"

    depends_on:
      - gluetun

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - WEBUI_PORT=8080

      # VueTorrent
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent

    volumes:
      # Configuração persistente
      - ${APP_DATA_DIR}/data/qbittorrent:/config

      # Mesmos downloads usados por Radarr/Sonarr/Transmission
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
