  gluetun:
    image: qmcgaw/gluetun:latest
    restart: on-failure

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

    env_file:
      - ${APP_DATA_DIR}/data/gluetun/nordvpn.env

    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - TZ=Europe/Lisbon

    volumes:
      - ${APP_DATA_DIR}/data/gluetun:/gluetun
